# Data Transform

In this notebook, we will ask you a series of questions to evaluate your findings from your EDA. Based on your response & justification, we will ask you to also apply a subsequent data transformation. 

If you state that you will not apply any data transformations for this step, you must **justify** as to why your dataset/machine-learning does not require the mentioned data preprocessing step.

The bonus step is completely optional, but if you provide a sufficient feature engineering step in this project we will add `1000` points to your Kahoot leaderboard score.

You will write out this transformed dataframe as a `.csv` file to your `data/` folder.

**Note**: Again, note that this dataset is quite large. If you find that some data operations take too long to complete on your machine, simply use the `sample()` method to transform a subset of your data.

In [4]:
import pandas as pd
import numpy as np

In [7]:
transactions = pd.read_csv("../data/bank_transactions.csv")

transactions.head()

sample_df = transactions.sample(n=5000)

## Q1

Does your model contain any missing values or "non-predictive" columns? If so, which adjustments should you take to ensure that your model has good predictive capabilities? Apply your data transformations (if any) in the code-block below.

Yes, my model contains non-predictive columns. NameDest and NameOrig contains it because it was used as a representative for customers. Adjustments that I would take to ensure to make my model has good predictive capabilities is by dropping those columns. I can use the drop function to remove them. I would first create a variable (saving it back) then do the drop function.

In [9]:
sample_df.drop(["nameDest", "nameOrig"], axis=1)

,type,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
385691,PAYMENT,2779.55,0.00,0.00,0.00,0.00,0,0
929671,PAYMENT,11187.65,0.00,0.00,0.00,0.00,0,0
455483,PAYMENT,28061.66,40857.00,12795.34,0.00,0.00,0,0
173606,TRANSFER,457299.81,151.00,0.00,538800.67,996100.48,0,0
676848,CASH_IN,26868.90,1163735.93,1190604.83,441895.38,415026.48,0,0
...,...,...,...,...,...,...,...,...
502408,CASH_OUT,125616.87,117915.00,0.00,5426928.16,5770169.23,0,0
789289,TRANSFER,7598282.26,3262.00,0.00,3450132.32,11048414.57,0,0
269884,CASH_OUT,379005.00,65759.00,0.00,3072419.34,3451424.34,0,0
307380,CASH_IN,348874.03,18492.00,367366.03,3514873.22,3165999.20,0,0
878799,CASH_OUT,199441.97,134748.00,0.00,107264.49,306706.46,0,0

## Q2

Do certain transaction types consistently differ in amount or fraud likelihood? If so, how might you transform the type column to make this pattern usable by a machine learning model? Apply your data transformations (if any) in the code-block below.

The transaction types shown amounts alike for isFraud and isFlaggedFraud. Cash out appeared twice in isFraud which beg to question if it is a replicate which can posssibly lead to fraud. A removal would need to take place in order to fix this matter.

## Q3

After exploring your data, you may have noticed that fraudulent transactions are rare compared to non-fraudulent ones. What challenges might this pose when training a machine learning model? What strategies could you use to ensure your model learns meaningful patterns from the minority class? Apply your data transformations (if any) in the code-block below.

The challenges posed is that the least selected transaction type, payment an debit, are unlikely to have any fraudulent transactions. The most used, transfer, shown significant signs of fraudulent transactions. The best approach to ensure my model learns meaningful patterns is to utilize the pearson correlation coefficient to quantify the strength and direction of the minority class.

In [10]:
transactions[["isFraud","amount"]].corr()

          isFraud    amount
isFraud  1.000000  0.069722
amount   0.069722  1.000000

## Bonus (optional)

Are there interaction effects between variables (e.g., fraud and high amount and transaction type) that aren't captured directly in the dataset? Would it be helpful to manually engineer any new features that reflect these interactions? Apply your data transformations (if any) in the code-block below.

Answer Here

In [2]:
# write out newly transformed dataset to your folder
...